### ISSUE TITLE
[Feature Request] add active presentation arrangement

### ISSUE THREAD

**Issue by aj-norman** [jeffmikels/ProPresenter-RemoteControl#15]
Hi, Apologies in advance if this is the wrong place to post this.

Can the presentation arrangements & current active arrangement be added to the `v1/presentation/{uuid}` and `v1/presentation/current` endpoints with the `current` endpoint also returning the current active group in the arrangement

I hope this is possible 

Thanks in advance

**Comment by jeffmikels** [comment]
The REST API does not return the arrangements, but the reverse-engineered `remote` websocket protocol does. Hopefully, one of these days, the folks at Renewed Vision will get the REST API to show the arrangements too.
